### ISSUE TITLE
Banner links to itself as resource by default 

### ISSUE THREAD

**Issue by eddiejaoude** [SashoStoichkov/SashoStoichkov#10]
The top banner links to itself on github, I think by default. It is not wrong/bad, but could possibly more useful to link somewhere else?

```html
<h1 align="center" width="100%">
  <img src="./GH Cover v.2.gif">
</h1>
```

![alex](https://user-images.githubusercontent.com/624760/111319368-d2b3a080-865d-11eb-8e15-683c7d8415d7.gif)

**Comment by SashoStoichkov** [comment]
Thank you @eddiejaoude for raising the issue 🤓 

Could you recommend where that link should redirect to?

**Comment by SashoStoichkov** [comment]
Now it redirects to my LinkedIn profile 👍🏻 Thanks @eddiejaoude for the suggestion

**Comment by eddiejaoude** [comment]
I think as long as it links somewhere useful that is the main thing 👍

**Comment by SashoStoichkov** [comment]
Yep 👍🏻
