### ISSUE TITLE
Error fetching the resource used in the README.md file

### ISSUE THREAD

**Issue by bishalr0y** [SashoStoichkov/SashoStoichkov#11]
Issue:
![Inkederror fetching_LI](https://user-images.githubusercontent.com/56751927/112344458-1ce5f300-8cea-11eb-8d20-91f08efbc4f5.jpg)

Cause:
![2](https://user-images.githubusercontent.com/56751927/112344578-3be48500-8cea-11eb-875b-b075cc039547.png)

The highlighted code shown above is trying to fetch resource from a link that is not valid.

**Comment by SashoStoichkov** [comment]
Thank you for raising the issue 👍🏻

**Comment by SashoStoichkov** [comment]
@bishalr0y Thank you for raising the issue but it seems to it have fixed itself 😅
