### ISSUE TITLE
Link to demo project probably wrong

### ISSUE THREAD

**Issue by schmelto** [SashoStoichkov/SashoStoichkov#4]
Worked over Django Styleguide example `project`
May you take a look at the link to the project it refers to the same URL as the Django style guide

**Comment by SashoStoichkov** [comment]
Hi @schmelto 👋🏻 and thank you for raising the issue 👍🏻 

I think that the links are different 🤔

**Comment by schmelto** [comment]
Yeah you're right :) need some more coffee ☕ my fault :)
