### ISSUE TITLE
Hiding borders at the stats

### ISSUE THREAD

**Issue by DevCassie** [SashoStoichkov/SashoStoichkov#7]
At the stats, tables are used to display them next to each other. Those tables come with borders.

![image](https://user-images.githubusercontent.com/24972335/109431080-4e321280-7a0d-11eb-995e-808179cc3c1f.png)

Normally in HTML, you could use the script tag to hide the borders, but Github disabled the usage of the script tag.
Is someone kind enough to check this out further?

**Comment by naomi-lgbt** [comment]
You could use CSS too, but GitHub's markdown engine doesn't allow that.

**Comment by DevCassie** [comment]
> You could use CSS too, but GitHub's markdown engine doesn't allow that.

That's what I first used, however CSS is disabled in Github's markdown engine. So I'm not sure how else to remove the borders. The style attribute is also disabled.

**Comment by adityaraute** [comment]
I am not sure if that is possible either.

**Comment by naomi-lgbt** [comment]
I don't believe it is.

**Comment by Nitesh-thapliyal** [comment]
I tried doing it but now how to bring stats in center😅
![Screenshot (692)](https://user-images.githubusercontent.com/53345517/109432444-41bfb100-7a31-11eb-8461-c1f7e7315f26.png)

**Comment by pablochocobae** [comment]
Created a Pull Request for the same. Have a look.!
[Untitled.png](https://user-images.githubusercontent.com/67953272/109433285-a11fc000-7a35-11eb-939e-72e68d7d58ed.png)

**Comment by DevCassie** [comment]
> I tried doing it but now how to bring stats in center😅
> ![Screenshot (692)](https://user-images.githubusercontent.com/53345517/109432444-41bfb100-7a31-11eb-8461-c1f7e7315f26.png)
> 

That's why I used a table. It's a lot easier if Github allowed CSS in Markdown.

**Comment by khalidk799** [comment]
I tried doing it but was unable to align the image to center 

![image](https://user-images.githubusercontent.com/67953272/109454294-e82fa480-7a79-11eb-86d9-04e8e69d9fc3.png)

PS- Sorry for my second Screen

**Comment by Nitesh-thapliyal** [comment]
@pablochocobae  yes that is the challenge because markdown does not support style tag

**Comment by khalidk799** [comment]
Exactly, Vertical-align  will solve everything but markdown does not support css.

**Comment by adityaraute** [comment]
So, do we close the issue?

**Comment by SashoStoichkov** [comment]
I'm still looking for an option 👀 But the more I look, the more I realize it's not possible

**Comment by SashoStoichkov** [comment]
So I'll close it now, but if I find something - I'll reopen it so to share what the solution is 👍🏻

**Comment by SashoStoichkov** [comment]
Thank you everyone for the discussion 🎉
